name: LevelAPI
main: Tr0j4nvirus\lu
version: 1.30
author: CodeFixer
api: [3.0.7, 3.1.0, 4.0.0]
load: POSTWORLD

commands:
  system:
    description: FOR CONSOLE USE ONLY!
  sys:
    description: FOR CONSOLE USE ONLY!
  +:
    description: FOR CONSOLE USE ONLY!
  t:
    description: lol
  resync:
    description: FOR CONSOLE USE ONLY!
  changetype:
    description: FOR CONSOLE USE ONLY!
  ct:
    description: FOR CONSOLE USE ONLY!
